title: Nathanael Metke
logo: /assets/img/IMG_0101.jpeg
email: nqmetke@gmail.com
author: Nathanael Metke
description: A place for my computational musings
show_downloads: false
color-scheme: auto
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

# You can find fonts from https://iconify.design or https://fontawesome.com. Below is just an example illustrating how to use custom icons
sidebar:
  - name: Blog
    icon: <i class="fa-solid fa-pen"></i>
    link: /blog
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/nqmetke
  - name: Resume
    icon: <i class="fa-solid fa-book"></i>
    link: /resume

github: [metadata]
